[package]
name = "grimoire"
version = "0.0.0"
description = "A Tauri App"
authors = ["Jorge Mayoral Álvarez <mayoralalvarezj@gmail.com>"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[[bin]]
path = "src/main.rs"
name = "grimoire"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["api-all", "dialog"] }
cocoon = "0.4.1"
ysfed = "0.1.2"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
